name: Deploy NPM App

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.11.0' 

      - name: Install Dependencies
        run: npm install

      - name: Build App
        run: npm run build


      #- name: Deploy to Hosting (Example: Netlify, Vercel, Firebase)
        #run: echo "Deploy command goes here"
